= Ansible 
Nick Hardiman <nick@silvan.uk>
:source-highlighter: highlight.js
:revdate: 26-09-2021

What fun can be had with Ansible Core and friends?

[NOTE]
====
These docs have nothing to do with any https://docs.ansible.com/[official Ansible docs].
====


Articles cover sysadmin tasks like these.  

* Git
* Jenkins
* Ansible Core 
 
All these articles have examples to run, so you can learn by doing. Hands on a keyboard. Break it and fix it. 



== Red Hat's management technology

Red Hat supports many tools for automation and management.

* https://www.redhat.com/en/technologies/management/ansible[Red Hat Ansible Automation Platform]
* https://www.redhat.com/en/technologies/management/satellite[Red Hat Satellite]
* https://www.redhat.com/en/technologies/management/insights[Red Hat Insights]

https://www.ansible.com/products/engine[Ansible Engine] is one of Red Hat's products in the Automation Platform. Ansible Engine is an automation system, good for provisioning new systems and deploying applications. 
Thousands of modules are included to manage Linux, Windows, on-premise network kit, off-premise cloud services, physical machines and virtual.


== get in touch

Something wrong? 
https://github.com/nickhardiman/articles-ansible/issues[Open an issue on GitHub].

