= add an ansible user 
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 12-10-2021


Tell ansible to set up an account for SSH

Create a remote account called ansible_user that ansible can use for SSH connections. 
This account will be authenticated using a key pair, and will have passwordless sudo access.


== for managed nodes only 

This account is for the managed nodes only. 
Don't set it up on the control node.


.ansible node accounts  
....
.------------------------------------------------------.  
|  host1                                               |
|                                                      |
|                                                      |
|   +-------------------+       +-------------------+  |
|   |  guest1           |       | guest2            |  |
|   |   control node    |       |   managed node    |  |
|   |                   | SSH   |                   |  |
|   |              nick +------>|ansible_user       |  |
|   |                   |       |                   |  |
|   +-------------------+       +-------------------+  |
.------------------------------------------------------.  
....

We even set this account up on the host machine, so the _guest1_ control node can treat _host1_ like a managed node. 
The concept of a guest virtual machine making changes on the host physical machine seems a little weird. 
But that's the way many provisioning systems work.  

.ansible SSH from guest to host 
....
.---------------------------------.  
|  host1                          |
|                                 |
|   +----------+                  |
|   |          |                  |
|   |  guest1  |                  |
|   |          |                  |
|   |  nick ---+---> ansible_user |
|   |          |                  |
|   +----------+                  |
.---------------------------------.  
....


Ansible playbooks will provision other guest VMs. 
Ansible is running in a guest VM, to keep messy development work off the host machine. 
Giving ansible power over the hypervisor means allowing a VM to make changes to its host. 

Sound like a security flaw? 
Sure does! This procedure adds a new user _ansible_user_ to the host and gives it full passwordless sudoers rights. 
In a shared environment, this DIY setup would be a headache. 
In production, it would be a disaster.
But it's fine for this self-contained development environment. 

A sysadmin can manually add a user to the managed host by running commands like `groupadd`, `useradd` and `ssh-copy-id`.


== check SSH from guest to host 

Check access. 
Use the address of the Internet gateway. 

[source,shell]
....
[nick@guest1 ~]$ ip route list
default via 192.168.122.1 dev eth0 proto dhcp metric 100 
192.168.122.0/24 dev eth0 proto kernel scope link src 192.168.122.100 metric 100 
[nick@guest1 ~]$ 
[nick@guest1 ~]$ ssh 192.168.122.1
nick@192.168.122.1's password: 
Web console: https://host.lab.example.com:9090/ or https://10.0.1.40:9090/

Last login: Mon Jun  1 17:37:25 2020 from 192.168.122.100
[nick@host1 ~]$ 
[nick@host1 ~]$ exit
logout
Connection to 192.168.122.1 closed.
[nick@guest1 ~]$
....

== create a key pair 






