= make the common git repository
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 02-06-2020


On guest1

== install  


Install git with the command ``sudo dnf install git``.
This installs the _git-core_ package and many perl modules. 


== configure a few things

Create a common group. 
Add a few users to this group.
These tasks are only done once. 

There are plenty of commands that need elevated privileges here. 
Rather than typing _sudo_ every time, use the root account. 


Create a common directory. 

[source,shell]
....
[nick@guest1 ~]$ sudo su -
[root@guest1 ~]# groupadd scm
[root@guest1 ~]# usermod -a -G scm nick
[root@guest1 ~]# 
[root@guest1 ~]# mkdir /var/git
....

Change the group ownership.

[source,shell]
....
[root@guest1 ~]# chown root.scm /var/git/
[root@guest1 ~]# 
[root@guest1 ~]# exit
logout
[nick@guest1 ~]$ 
....

Add git user configuration. 

Configure git. 
Otherwise, committing the file fails with a 'fatal: empty ident name not allowed' error. 

[source,shell]
....
[nick@guest1 ~]$ git config --global user.email "nick@lab.example.com"
[nick@guest1 ~]$ git config --global user.name "Nick Hardiman"
[nick@guest1 ~]$ 
[nick@guest1 ~]$ cat .gitconfig 
[user]
	email = nick@lab.example.com
	name = Nick Hardiman
[nick@guest1 ~]$ 
....


== create a common repository 

Create a common git repo to share with the group. 

These tasks are repeated for every new git repo. 

[source,shell]
....
[nick@guest1 ~]$ sudo su -
[root@guest1 ~]#  cd /var/git/
[root@guest1 git]# NEW_REPO=content1.git
[root@guest1 git]# git init --bare --shared=group $NEW_REPO
Initialized empty shared Git repository in /var/git/content1.git/
[root@guest1 git]# 
[root@guest1 git]# chgrp -R scm $NEW_REPO
[root@guest1 git]# 
[root@guest1 git]# exit
logout
[nick@guest1 ~]$ 
....

