= clone using SSH
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 25-09-2021




== clone the central repo 

Clone the new shared repo for your personal use. 
Copy the repo to your home directory with git clone. 

This |_git clone_ command uses SSH to connect to a host.  

[source,shell]
....
git clone <user>@<host>:<directory>
....

Some SSH security messages appear. 

[source,shell]
....
[nick@guest1 ~]$ git clone scm@git1.lab.example.com:/var/git/content1.git
Cloning into 'content1'...
The authenticity of host 'git1.lab.example.com (192.168.1.217)' can't be established.
ECDSA key fingerprint is SHA256:bI6WTnvVehkwr5ZoUlXJzONyk2/kEwGIX4f+enmJpRs.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'git1.lab.example.com,192.168.1.217' (ECDSA) to the list of known hosts.
....

A warning appears about a suspiciously empty directory. 
The new _content1_ directory appears, and does contain a _.git_ directory. 

[source,shell]
....
warning: You appear to have cloned an empty repository.
[nick@guest1 ~]$ 
[nick@guest1 ~]$ ls -a content1/
.  ..  .git
[nick@guest1 ~]$ 
....

If a password prompt appears, there is probably a public key problem. 

[source,shell]
....
[nick@guest1 gittest]$ git clone scm@git1.lab.example.com:/var/git/content1.git
...
scm@git1.lab.example.com's password: 
....


Check remotes

[source,shell]
....
[nick@guest1 content1]$ git remote -v
origin	scm@git1.lab.example.com:/var/git/content1.git (fetch)
origin	scm@git1.lab.example.com:/var/git/content1.git (push)
[nick@guest1 content1]$ 
....




== add git user configuration

Configure git. 
Otherwise, committing the file causes git to complain that it had to guess at who the author is. 

[source,shell]
....
[nick@guest1 content1]$ git config --global user.email "nick@lab.example.com"
[nick@guest1 content1]$ 
[nick@guest1 content1]$ git config --global user.name "Nick Hardiman"
[nick@guest1 content1]$ 
[nick@guest1 content1]$ cat ~/.gitconfig 
[user]
	email = nick@lab.example.com
	name = Nick Hardiman
[nick@guest1 content1]$ 
....


