= clone using SSH
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 25-09-2021


== which network transport 

There are a few ways to set up authentication and file transfer. 
We could use NFS, web, SSH or git's own protocol, also called git. 
Which access protocol is the easiest to set up?

We want multiple locations to access git over the network. This git service will be accessed from other guest machines. That means setting up a service to handle network transport. There are a few choices -  which is best? 
(spoiler - it's SSH)

* simple file-based repository with NFS. A file-based repo is a local solution, not a network solution. Install NFS to share the same files among many machines. Allow NFS traffic on firewalls.
* dumb HTTP service. Install Apache, then set up read-only HTTP access for reading. Doesn't handle writing - that requires another service. Allow web traffic on firewalls.
* smart HTTP service. Install Apache, then configure a new site with WebDAV read/write access. Open firewalls.
* git. Practically no work to do, and practically no security either - allow the world to read and write everything. Make sure git's in a trusted place and open git port 9418 on firewalls.
* SSH. There's no install work to do because it's already running. And no security work either, because SSH handles access control and traffic encryption. SSH port 22 is already open on firewalls. 


== create a personal repository 

Clone the new shared repo for your personal use. 
Copy the repo to your home directory with git clone. 

This command uses SSH to connect to the git host. Some SSH security messages appear. 

[source,shell]
....
[nick@guest1 ~]$ git clone git1:/var/git/content1.git
Cloning into 'content1'...
The authenticity of host 'git1 (192.168.122.4)' can't be established.
ECDSA key fingerprint is SHA256:nTrTxkZuJVURnVOqoC563D7F4yd3fnWOMewJBeL7bXw.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'git1,192.168.122.4' (ECDSA) to the list of known hosts.
....

A warning appears about the suspiciously empty directory. 

[source,shell]
....
warning: You appear to have cloned an empty repository.
[nick@guest1 ~]$ 
[nick@guest1 ~]$ ls -a content1/
.  ..  .git
[nick@guest1 ~]$ 
....


== create content 

Create a bash script on guest1.
The script is created by a one-liner command, which requires some tricky quoting and the special character \n.

[source,shell]
....
[nick@guest1 ~]$ cd content1/
[nick@guest1 content1]$ echo -e '#!'"/bin/bash\necho 'hello world'\n" > hello-world.sh
[nick@guest1 content1]$ chmod 754 ./hello-world.sh 
....

Does it work? 

[source,shell]
....
[nick@guest1 content1]$ ./hello-world.sh 
hello world
[nick@guest1 content1]$ 
....

Time to store a copy somewhere safe. 



== commit to both repositories 

Commit the new file to your personal repo. 

[source,shell]
....
[nick@guest1 content1]$ git add hello-world.sh 
[nick@guest1 content1]$ git commit -m 'create hello-world.sh'
[master (root-commit) 540c540] create hello-world.sh
 1 file changed, 3 insertions(+)
 create mode 100755 hello-world.sh
[nick@guest1 content1]$ 
....

Copy to the shared repo.

[source,shell]
....
[nick@guest1 content1]$ git push 
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 262 bytes | 262.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To git1:/var/git/content1.git
 * [new branch]      master -> master
[nick@guest1 content1]$
....


== set up key-based login 

We have to type in our account password every time the remote repository is accessed. 

!!! no it doesnt

That gets tiresome. 
Git provides credential helpers for web access, but not for SSH. 
Set up public key access so SSH won't prompt for a password. 

Append your public key to the list of authorized keys. 

[source,shell]
----
[nick@guest1 content1]$ cd
[nick@guest1 ~]$ cat .ssh/id_rsa.pub  >> .ssh/authorized_keys 
[nick@guest1 ~]$ 
----

Check.

[source,shell]
----
[nick@guest1 content1]$ ssh git1.lab.example.com
The authenticity of host 'git1.lab.example.com (192.168.122.4)' can't be established.
ECDSA key fingerprint is SHA256:nTrTxkZuJVURnVOqoC563D7F4yd3fnWOMewJBeL7bXw.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'git1.lab.example.com' (ECDSA) to the list of known hosts.
Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Fri Jul  3 12:58:51 2020 from 192.168.122.1
[nick@guest1 ~]$ 
[nick@guest1 ~]$ logout
Connection to git1.lab.example.com closed.
[nick@guest1 content1]$ 
----

