= clone using SSH
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 25-09-2021


== which network transport 

There are a few ways to set up authentication and file transfer. 
We could use NFS, web, SSH or git's own protocol, also called git. 
Which access protocol is the easiest to set up?

We want multiple locations to access git over the network. This git service will be accessed from other guest machines. That means setting up a service to handle network transport. There are a few choices -  which is best? 
(spoiler - it's SSH)

* simple file-based repository with NFS. A file-based repo is a local solution, not a network solution. Install NFS to share the same files among many machines. Allow NFS traffic on firewalls.
* dumb HTTP service. Install Apache, then set up read-only HTTP access for reading. Doesn't handle writing - that requires another service. Allow web traffic on firewalls.
* smart HTTP service. Install Apache, then configure a new site with WebDAV read/write access. Open firewalls.
* git. Practically no work to do, and practically no security either - allow the world to read and write everything. Make sure git's in a trusted place and open git port 9418 on firewalls.
* SSH. There's no install work to do because it's already running. And no security work either, because SSH handles access control and traffic encryption. SSH port 22 is already open on firewalls. 


== add your public key to git's list of authorized keys

??? was ssh-keygen mentioned before

SSH refuses to work if any old geezer has permission to look at files. 

[source,shell]
.... 
[root@guest1 ~]# mkdir /home/scm/.ssh
[root@guest1 ~]# chmod 700 /home/scm/.ssh
[root@guest1 ~]# 
[root@guest1 ~]# cat  /home/nick/.ssh/id_rsa.pub >> /home/scm/.ssh/authorized_keys
[root@guest1 ~]# chmod 600 /home/scm/.ssh/authorized_keys
[root@guest1 ~]# 
....

Fix ownership. 

[source,shell]
.... 
[root@guest1 ~]# chown -R scm.scm /home/scm/.ssh/
[root@guest1 ~]# 
....


== create a personal repository 

Clone the new shared repo for your personal use. 
Copy the repo to your home directory with git clone. 

This |_git clone_ command uses SSH to connect to a host.  

[source,shell]
....
git clone <user>@<host>:<directory>
....

Some SSH security messages appear. 

[source,shell]
....
[nick@guest1 ~]$ git clone scm@git1.lab.example.com:/var/git/content1.git
Cloning into 'content1'...
The authenticity of host 'git1.lab.example.com (192.168.1.217)' can't be established.
ECDSA key fingerprint is SHA256:bI6WTnvVehkwr5ZoUlXJzONyk2/kEwGIX4f+enmJpRs.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'git1.lab.example.com,192.168.1.217' (ECDSA) to the list of known hosts.
....

A warning appears about a suspiciously empty directory. 
The new _content1_ directory appears, and does contain a _.git_ directory. 

[source,shell]
....
warning: You appear to have cloned an empty repository.
[nick@guest1 ~]$ 
[nick@guest1 ~]$ ls -a content1/
.  ..  .git
[nick@guest1 ~]$ 
....


== create content 

Create a bash script on guest1.
The script is created by a one-liner command, which requires some tricky quoting and the special character \n.

[source,shell]
....
[nick@guest1 ~]$ cd content1/
[nick@guest1 content1]$ echo -e '#!'"/bin/bash\necho 'hello world'\n" > hello-world.sh
[nick@guest1 content1]$ chmod 754 ./hello-world.sh 
....

Does it work? 

[source,shell]
....
[nick@guest1 content1]$ ./hello-world.sh 
hello world
[nick@guest1 content1]$ 
....

Time to store a copy somewhere safe. 

== add git user configuration

Configure git. 
Otherwise, committing the file causes git to complain that it had to guess at who the author is. 

[source,shell]
....
[nick@guest1 content1]$ git config --global user.email "nick@lab.example.com"
[nick@guest1 content1]$ 
[nick@guest1 content1]$ git config --global user.name "Nick Hardiman"
[nick@guest1 content1]$ 
[nick@guest1 content1]$ cat ~/.gitconfig 
[user]
	email = nick@lab.example.com
	name = Nick Hardiman
[nick@guest1 content1]$ 
....



== update both repositories 

Commit the new file to your personal repo. 

[source,shell]
....
[nick@guest1 content1]$ git add hello-world.sh 
[nick@guest1 content1]$ git commit -m 'create hello-world.sh'
[master (root-commit) 540c540] create hello-world.sh
 1 file changed, 3 insertions(+)
 create mode 100755 hello-world.sh
[nick@guest1 content1]$ 
....

Copy to the shared repo.

[source,shell]
....
[nick@guest1 content1]$ git push 
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 262 bytes | 262.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To git1:/var/git/content1.git
 * [new branch]      master -> master
[nick@guest1 content1]$
....


== check both repositories 

Check your git log looks like the log of the shared repo 

Check your local repo's git log.

[source,shell]
....
[nick@guest1 content1]$ git log
commit 6ac7168a652d9afdb0457f9d07166ef4401881fe (HEAD -> master, origin/master)
Author: nick <nick@guest1.lab.example.com>
Date:   Mon Oct 18 23:05:54 2021 +0100

    create hello-world.sh
[nick@guest1 content1]$ 
....

Check the shared repo's git log. 

[source,shell]
....
[nick@guest1 content1]$ sudo su - scm
Last login: Mon Oct 18 22:57:59 BST 2021 on pts/0
[scm@guest1 ~]$ 
[scm@guest1 ~]$ cd /var/git/content1.git/
[scm@guest1 content1.git]$ 
[scm@guest1 content1.git]$ git log
commit 6ac7168a652d9afdb0457f9d07166ef4401881fe (HEAD -> master)
Author: nick <nick@guest1.lab.example.com>
Date:   Mon Oct 18 23:05:54 2021 +0100

    create hello-world.sh
[scm@guest1 content1.git]$ 
[scm@guest1 content1.git]$ logout
[nick@guest1 content1]$ 
....
