= create a kickstart file for controller1 
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 11-01-2021

The virtual machine _controller1_ is the platform we build on.
Create a file to define how the operating system should organize the resources - how to partition the disk, what extra RPM packages to install, user accounts to create and so on. 
This definition file is a Red Hat Kickstart file named controller1.ks.

This machine will be built using a *fresh install* build process, as opposed to a golden image build process. 

This procedure is similar to xref:rhel:virtual-machine:guest1-kickstart-file.adoc[].


== create a kickstart file

Create a new https://en.wikipedia.org/wiki/Kickstart_(Linux)[kickstart] file.
This file will contain all the configuration instructions for the kickstart program to follow. 

The naming policy for this file is "__machine_name__.ks". 
This kickstart config file goes in the _libvirt_ directory, along with bridge scripts and libvirt XML definitions. 

Keep config files in one place. 
Use a directory named _ansible_. 

[source,shell]
....
[nick@host1 ~]$ mkdir ansible
[nick@host1 ~]$ 
[nick@host1 ~]$ cd ~/ansible/
[nick@host1 ansible]$ 
....

Search Red Hat's    
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_an_advanced_rhel_installation/kickstart-commands-and-options-reference_installing-rhel-as-an-experienced-user[list of commands] to find an explanation of each line. 

Edit a new file. 

[source,shell]
....
[nick@host1 ansible]$ vim control.ks
....

Add this content. 
Copy and paste is fine. 
There is one change to make, in a later step. 

[source,kickstart]
....
# kickstart file for control.lab.example.com
# for further information, see Appendix B. Kickstart commands and options reference
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_an_advanced_rhel_installation/kickstart-commands-and-options-reference_installing-rhel-as-an-experienced-user
# install
# don't use graphical install
text
# look for an installer DVD
cdrom
# Run the Setup Agent on first boot
firstboot --enable

# l10n (localization)
lang en_GB.UTF-8
timezone Europe/London --isUtc
keyboard uk

# network
network  --bootproto=dhcp --device=enp1s0 --ipv6=auto --activate
network  --hostname=control.lab.example.com

# licences and repos
# And have a look at the "subscription" section, in the post section below. 
repo --name="AppStream" --baseurl=file:///run/install/repo/AppStream
eula --agreed

# accounts
# The command "openssl passwd  -6 --salt SQXqGsYna84.3SL5" turns "Password;1" into this. 
rootpw --iscrypted $6$SQXqGsYna84.3SL5$gJw6v23ZZ7WEITfBoZmyNDsIKeoqhS2Mwfk.KpCRloK7EfxlhL3MAlTCO33fr7QRfoG.GvBH1seWtQqz5v82q1
# same password, different salt (the first 16 characters after $6$)
user --groups=wheel --name=nick --password=$6$G3GIlnUH.JqcrAQl$I.q7gGoT37tcNnrGiHkeUTBtr8AAuoM/yy3P3FuEpJaSun6clgR8GlvKIbqOTgqNe.fIBV6xZOPiWvsduhXeC/ --iscrypted --gecos="nick"

# storage 
ignoredisk --only-use=vda
# partitions
clearpart --all --initlabel
part /boot/efi --fstype="efi"   --ondisk=vda --size=600 --fsoptions="umask=0077,shortname=winnt"
part pv.217    --fstype="lvmpv" --ondisk=vda --size=25000
part /boot     --fstype="xfs"   --ondisk=vda --size=1024
# LVM
volgroup rhel --pesize=4096 pv.217
logvol /     --fstype="xfs"  --size=1024  --name=root --vgname=rhel --grow
logvol swap  --fstype="swap" --size=256   --name=swap --vgname=rhel

# applications and services 
# Do not configure the X Window System
skipx

# done
# skip anaconda's prompt "Installation complete. Press ENTER to quit:"
reboot


# special install sections
%packages
# This is a group of packages. 
# To view the full list of groups, run
#   dnf group list --hidden
@^minimal-environment

%end

# password policy (for the anaconda installer, not PAM)
%anaconda
pwpolicy root --minlen=6 --minquality=1 --notstrict --nochanges --notempty
pwpolicy user --minlen=6 --minquality=1 --notstrict --nochanges --emptyok
pwpolicy luks --minlen=6 --minquality=1 --notstrict --nochanges --notempty
%end

# last jobs
%post --log=/root/ks-post.log
# subscription
/usr/sbin/subscription-manager register --username=nick --password='some password!' 
/usr/sbin/subscription-manager attach  --pool=123456789abcdef123456789abcdef12
# package update
/usr/bin/dnf -y update 
%end
....

Save your work. 


== customize the file

Edit the file. 

Change subscription manager values.
Change this line to match your developer account.
This is the user name and password for https://access.redhat.com/, https://developers.redhat.com/ and https://console.redhat.com/.

[source,kickstart]
....
/usr/sbin/subscription-manager register --username=nick --password='some password!' 
....

Change this line to match your pool ID (a long subscription key that looks like 123456789abcdef123456789abcdef12). 
To find your pool ID, run this command on the host _host1_. `sudo subscription-manager list --consumed`

[source,kickstart]
....
/usr/sbin/subscription-manager attach  --pool=123456789abcdef123456789abcdef12
....

Save your work. 


== check the kickstart file 

The kickstart validation utility _ksvalidator_ provides a static analysis of the new file.

Validate the file. 
No news is good news. 

[source,shell]
....
[nick@host1 libvirt]# ksvalidator control.ks 
[nick@host1 libvirt]# 
....

This static code analyzer is handy for catching typos, like typing _%edn_ instead of _%end_.

[source,shell]
....
[nick@host1 ansible]$ ksvalidator control.ks
The following problem occurred on line 79 of the kickstart file:

Section %post does not end with %end.

[nick@host1 ansible]$ 
....

