= create a python virtualenv 
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 29-05-2020

Create a python virtual environment.

Python developers 
https://packaging.python.org/tutorials/installing-packages/#creating-virtual-environments[create virtual environments] to keep their workspaces seperate. 

You can create a virtual environment using the platform copy of Python, with the command ``/usr/libexec/platform-python3.6 -m venv my-project``. 
But this is really meant for system use. 


== create a python virtual environment 

???
--system-site-packages
https://liquidat.wordpress.com/2019/08/30/howto-get-a-python-virtual-environment-running-on-rhel-8/
python3.6 -m venv --system-site-packages myvirtual_venv

selinux 
???

Run the command __python3 -m venv (new virtual environment)__. 

There is a command-line tool called http://pypi.python.org/pypi/virtualenv[virtualenv] which does the same thing.
This tool can be installed usng the RPM package ``python3-virtualenv``.
This package has some version baggage - installing the package _python3-virtualenv_ enables the module _python36_. 

Create a virtual environment using Python 3 and the venv module. 

[source,shell]
----
[nick@control ~]$ python3 -m venv new/virtual/environment
[nick@control ~]$ ls new/virtual/environment/
bin  include  lib  lib64  pyvenv.cfg
[nick@control ~]$ 
----

This creates a new path with hundreds of files in it, including pip. 

[source,shell]
----
[nick@control ~]$ new/virtual/environment/bin/pip --version
pip 19.2.3 from /home/nick/new/virtual/environment/lib64/python3.8/site-packages/pip (python 3.8)
[nick@control ~]$ 
----

== use the python virtual environment 

Using a python virtual environment changes your working environment. 
Try running ``env`` and looking at the variables PATH, PS1 and  VIRTUAL_ENV.

[source,shell]
----
[nick@control ~]$ source new/virtual/environment/bin/activate 
(environment) [nick@control ~]$ 
----

This developer environment is now in use. 


== customize the virtual environment 

* Upgrade packages. ``pip install --upgrade pip setuptools``
* Install packages. ``pip install yamllint``
* Run a command. ``python -c 'print("Hello, World!")'``



== clean up 

Remove the virtual environment. 

[source,shell]
----
(environment) [nick@control ~]$ deactivate
[nick@control ~]$ 
[nick@control ~]$ rm -r new
[nick@control ~]$ 
----





