= install python
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 29-05-2020


How Python developers can go from nothing to two versions of Python on RHEL8. 

duplicate of this?
https://developers.redhat.com/rhel8/hw/python/

If you are doing Python work - programming, or installing modules, or running third party Python apps - you need your own copy of Python. 

There are plenty of tools in the *appstream* repo that require Python, like ansible.
The user doesn't need to install Python to get these to work - the OS has its own copy of Python, called platform-python. 
Don't use platform-python for your own work. 
Developer environments are often broken. 
If you break the system's python, you break some system tools too.


Directory  ``/usr/lib/python3.6/site-packages/`` contains many Python modules. 
These were also installed via RPM packages when the system was built. 
There are dozens of these packages, from ``python3-asn1crypto`` to ``python3-urllib3``.
https://fedoraproject.org/wiki/DNF[DNF] history shows the package list. 


[source,shell]
----
[nick@guest1 ~]# sudo dnf history info 1 | grep python
    Install python3-asn1crypto-0.24.0-3.el8.noarch                                    @anaconda
    Install python3-audit-3.0-0.17.20191104git1c2f876.el8.x86_64                      @anaconda
    Install python3-cffi-1.11.5-5.el8.x86_64                                          @anaconda
...
----


== list DNF modules 

Three modules are available to make installing an older version easier. 
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_managing_and_removing_user-space_components/introduction-to-modules_using-appstream[dnf module streams] are available for Python 2.7,  3.6 and 3.8.  


This ``dnf`` command is not run as root, so permission warnings appear. This is a safe read-only command, and works fine despite these permission problems. 

[source,shell]
----
[nick@guest1 ~]$ dnf module list python*
2020-05-26 11:59:31,423 [ERROR] dnf:2357:MainThread @logutil.py:194 - [Errno 13] Permission denied: '/var/log/rhsm/rhsm.log' - Further logging output will be written to stderr
Not root, Subscription Management repositories not updated
Red Hat Enterprise Linux 8 for x86_64 - AppStre 5.5 MB/s |  18 MB     00:03    
Red Hat Enterprise Linux 8 for x86_64 - BaseOS  5.7 MB/s |  18 MB     00:03    
Last metadata expiration check: 0:00:03 ago on Tue 26 May 2020 11:59:41 EDT.
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
Name       Stream   Profiles           Summary                                  
python27   2.7 [d]  common [d]         Python programming language, version 2.7 
python36   3.6 [d]  build, common [d]  Python programming language, version 3.6 
python38   3.8 [d]  build, common [d]  Python programming language, version 3.8 

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled
[nick@guest1 ~]$ 
----

The two python38 profiles *build* and *common* are similar. 
Both contain a selection of programs including 
https://docs.python.org/3/[python3], 
https://pip.pypa.io/en/stable/user_guide/[pip3] and 
https://setuptools.readthedocs.io/en/latest/[setuptools], 
but _build_ includes a few more tools for compiling programs and building RPM packages. 



== install python36/build

This minor release is maintained for the entire life of RHEL 8. 

[source,shell]
----
sudo dnf module install python38/build
----

Errr, this is the common profile 

[source,shell]
----
[nick@control ~]$ sudo dnf module install python36
Updating Subscription Management repositories.
Last metadata expiration check: 0:16:24 ago on Fri 15 Oct 2021 11:07:38 BST.
Dependencies resolved.
================================================================================
 Package            Arch   Version       Repository                        Size
================================================================================
Installing group/module packages:
 python36           x86_64 3.6.8-2.module+el8.1.0+3334+5cb623d7
                                         rhel-8-for-x86_64-appstream-rpms  19 k
Installing dependencies:
 python3-pip        noarch 9.0.3-19.el8  rhel-8-for-x86_64-appstream-rpms  20 k
 python3-setuptools noarch 39.2.0-6.el8  rhel-8-for-x86_64-baseos-rpms    163 k
Installing module profiles:
 python36/common                                                               
Enabling module streams:
 python36                  3.6                                                 

Transaction Summary
================================================================================
Install  3 Packages

Total download size: 201 k
Installed size: 466 k
Is this ok [y/N]: 
----

This places commands ``python3`` and ``pip3`` in /usr/bin/.



=== use alternatives to link python to python3 

The _alternatives_ tool points a default command at one of a list of alternatives. 
It can be used to make the ``python`` command run either v2 or v3. 

 alternatives has no configuration for other Python tools, so it can't be used to point pip to pip3. 


[source,shell]
....
[nick@guest1 ~]$ sudo alternatives --config python
[sudo] password for nick: 

There is 4 program that provides 'python'.

  Selection    Command
-----------------------------------------------
*+ 1           /usr/libexec/no-python
   2           /usr/bin/python2
   3           /usr/bin/python3
   4           /usr/bin/python3.8

Enter to keep the current selection[+], or type selection number: 3
[nick@guest1 ~]$ 
....

The _alternatives_ tool works by creating a chain of symlinks. The python command takesa pretty indirect route to get to python3: /usr/bin/python -> /etc/alternatives/unversioned-python -> /usr/bin/python3 -> /etc/alternatives/python3 --> /usr/bin/python3.8.

[source,shell]
....
[nick@guest1 ~]$ which python
/usr/bin/python
[nick@guest1 ~]$ python --version
Python 3.6.8
[nick@guest1 ~]$ 
....

