= use ansible-navigator
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 17-03-2021

A newer shinier ansible-playbook


== install 

v2.0 on RHEL 8

[source,shell]
----
subscription-manager repos  --enable ansible-automation-platform-2.0-early-access-for-rhel-8-x86_64-rpms
yum install ansible-navigator
----

v2.2 on RHEL 9

[source,shell]
----
[root@host2 ~]#  subscription-manager repos --enable ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms
Repository 'ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms' is enabled for this system.
[root@host2 ~]# 
[root@host2 ~]# dnf install ansible-navigator
Updating Subscription Management repositories.
Red Hat Ansible Automation Platform 2.2 for RHEL 9 x86_64 (RPMs)              1.4 MB/s | 964 kB     00:00    
Dependencies resolved.
==============================================================================================================
 Package                 Arch   Version          Repository                                              Size
==============================================================================================================
Installing:
 ansible-navigator       noarch 2.1.0-1.el9ap    ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms 366 k
Installing dependencies:
 ansible-builder         noarch 1.1.0-3.el9ap    ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms  45 k
 ansible-runner          noarch 2.2.1-1.el9ap    ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms 7.8 k
 python3-ansible-runner  noarch 2.2.1-1.el9ap    ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms 120 k
 python3-attrs           noarch 21.4.0-2.el9pc   ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms  93 k
 python3-bindep          noarch 2.10.2-3.el9ap   ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms  58 k
 python3-daemon          noarch 2.3.0-4.el9ap    ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms  38 k
 python3-distro          noarch 1.6.0-3.el9pc    ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms  34 k
 python3-docutils        noarch 0.16-4.el9ap     ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms 1.5 M
 python3-jsonschema      noarch 3.2.0-13.el9     rhel-9-for-x86_64-appstream-rpms                       129 k
 python3-lockfile        noarch 1:0.12.2-1.el9ap ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms  34 k
 python3-onigurumacffi   x86_64 1.1.0-2.el9ap    ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms  25 k
 python3-parsley         noarch 1.3-2.el9pc      ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms 169 k
 python3-pbr             noarch 5.8.1-2.el9ap    ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms 137 k
 python3-pyrsistent      x86_64 0.17.3-8.el9     rhel-9-for-x86_64-appstream-rpms                       118 k
 python3-requirements-parser
                         noarch 0.2.0-4.el9ap    ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms  21 k

Transaction Summary
==============================================================================================================
Install  16 Packages
...       
Complete!
[root@host2 ~]# 
----


== use 

[source,shell]
----
[root@host2 ~]# ansible-navigator run --help
Usage: ansible-navigator run [options]

run: Run a playbook

Options (global):
 -h     --help                                   Show this help message and
                                                 exit
...
Note: 'ansible-navigator run' additionally supports the same parameters as the
'ansible-playbook' command. For more information about these, try 'ansible-
navigator run --help-playbook --mode stdout'
[root@host2 ~]# 
----


== container ee-supported-rhel8

The tool uses a container for jobs. It's the same as an execution environment.
By default ansible-navigator uses one of the ee containers, ee-supported-rhel8. 

ansible-navigator tries to pull a copy of the container from Red Hat's central registry. 
If the container is not available, the tool fails with the error  _Execution environment pull failed_.

[source,shell]
----
[root@host2 ~]# ansible-navigator doc shell
--------------------------------------------------------------------------------------------------------------
Execution environment image and pull policy overview
--------------------------------------------------------------------------------------------------------------
Execution environment image name:     registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest
Execution environment image tag:      latest
Execution environment pull arguments: None
Execution environment pull policy:    tag
Execution environment pull needed:    True
--------------------------------------------------------------------------------------------------------------
Updating the execution environment
--------------------------------------------------------------------------------------------------------------
Running the command: podman pull registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest
Trying to pull registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest...
Error: initializing source docker://registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest: unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
  Error: Execution environment pull failed
   Hint: Check the execution environment image name, connectivity to and
         permissions for the registry, and try again
[root@host2 ~]# 
----

Log into the central repository. 

[source,shell]
----
[root@host2 ~]# podman login -u my-dev-account -p 'my-password' registry.redhat.io
Login Succeeded!
[root@host2 ~]# 
----

Re-run the command. 
The container downloads

[source,shell]
----
[root@host2 ~]# ansible-navigator doc shell
...
Trying to pull registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob a9dacd757072 [=====>-----------------------------] 7.0MiB / 41.0MiB
Copying blob bddb6822d87e [============>----------------------] 6.8MiB / 18.3MiB
Copying blob a96e4e55e78a [===============>------------------] 16.8MiB / 34.8MiB
Copying blob 67d8ef478732 done  
Copying blob 50223de3f59a [===>-----------------------------] 25.6MiB / 199.5MiB
----

The OS stores a local copy of the container (try grep /etc/containers).

[source,shell]
----
[root@host2 ~]# podman images --all
REPOSITORY                                                            TAG         IMAGE ID      CREATED      SIZE
registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8  latest      d2595109e44f  3 weeks ago  1.45 GB
[root@host2 ~]# 
----

== "ansible-navigator doc" is like "ansible-doc"

[source,shell]
----
[root@host2 ~]# ansible-navigator doc shell
...
----

The manual page appears in a pager. 

[source,shell]
----
Name: shell (module)                                                            
  0│---                                                                        ▒
  1│doc:                                                                       ▒
...
 39│    M(ansible.builtin.shell) module is explicitly required. When running ad-
 40│    use your best judgement.
^b/PgUp page up    ^f/PgDn page down    ↑↓ scroll    esc back    :help help
----


== stdout or interactive interface 

[source,shell]
----
ansible-navigator doc shell --mode stdout
----

== image pull policy

Default pull policy is tag, so any image tagged with latest is always pulled. 
For more information, see https://ansible-navigator.readthedocs.io/en/latest/settings/[settings].

[source,shell]
----
ansible-navigator doc shell --pull-policy missing
----

== "ansible-navigator run" is like "ansible-playbook"

Run a simple ping playbook.
Use the locally stored image by setting a different pull policy. 
Don't use the interactive interface. 

[source,shell]
----
[root@host2 ~]# ansible-navigator run ansible/ping-playbook.yml --mode stdout  --pull-policy=missing
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [ping] ********************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
[root@host2 ~]# 
----

